version: "3"
services:
  frontend:
    build:
      context: "frontend/"
    environment:
      - "API_HOST:http://localhost:5000"
    ports:
      - "3000:3000"
  backend:
    build:
      context: "backend/"
    ports:
      - "5000:5000"
